apiVersion: v1
kind: Service
metadata:
  name: envoy-gw-infra-metrics
  namespace: gateway
  labels:
    app: envoy-gw-infra-metrics
spec:
  selector:
    app: envoy-gw-dataplane
  ports:
    - name: metrics
      port: 19001
      targetPort: 19001
