apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: {{ .Values.envoyProxy.name | quote }}
  namespace: {{ .Values.envoyProxy.namespace | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "-6"
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        {{- if .Values.envoyProxy.service.type }}
        type: {{ .Values.envoyProxy.service.type | quote }}
        {{- end }}

        {{- with .Values.envoyProxy.service.annotations }}
        annotations:
{{ toYaml . | nindent 10 }}
        {{- end }}

        {{- with .Values.envoyProxy.service.loadBalancerIP }}
        loadBalancerIP: {{ . | quote }}
        {{- end }}

      envoyDeployment:
        {{- with .Values.envoyProxy.deploymentName }}
        name: {{ . | quote }}
        {{- end }}
        {{- if not .Values.keda.enabled }}
        replicas: {{ .Values.envoyProxy.replicas }}
        {{- end }}
        pod:
          {{- if .Values.envoyProxy.podLabels }}
          labels:
{{ toYaml .Values.envoyProxy.podLabels | nindent 12 }}
          {{- end }}

          {{- if .Values.envoyProxy.topologySpreadConstraints }}
          topologySpreadConstraints:
{{ toYaml .Values.envoyProxy.topologySpreadConstraints | nindent 12 }}
          {{- end }}
