apiVersion: v1
kind: Service
metadata:
  name: gateway-health
  namespace: gateway
  labels:
    app: gateway-health
spec:
  selector:
    app: gateway-health
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP