{{- if and .Values.autoscaling.enabled (not .Values.keda.enabled) }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ printf "%s-dataplane" .Values.envoyProxy.name | quote }}
  namespace: {{ .Values.envoyProxy.namespace | quote }}
  annotations:
    # EnvoyProxy(-6) 이후, dataplane 생성 후 동작하도록 뒤로 배치
    argocd.argoproj.io/sync-wave: "6"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ (.Values.envoyProxy.deploymentName | default .Values.envoyProxy.name) | quote }}

  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}

  {{- with .Values.autoscaling.behavior }}
  behavior:{{ toYaml . | nindent 4 }}
  {{- end }}

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ dig "autoscaling" "cpu" "averageUtilization" 60 .Values }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ dig "autoscaling" "memory" "averageUtilization" 70 .Values }}
{{- end }}

