apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ceph-csi
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://ceph.github.io/csi-charts
    chart: ceph-csi-cephfs
    targetRevision: 3.16.0
    helm:
      parameters:
        # 1. 기본 접속 정보
        - name: csiConfig[0].clusterID
          value: "491b725b-d483-48ea-855a-b78b5b1bdc91"
        - name: csiConfig[0].monitors[0]
          value: "10.10.10.101:6789"
        - name: csiConfig[0].monitors[1]
          value: "10.10.10.102:6789"
        - name: csiConfig[0].monitors[2]
          value: "10.10.10.103:6789"

        # 2. [핵심] 호스트 네트워크 사용 (IP 대역 문제 해결)
        - name: provisioner.enableHostNetwork
          value: "true"
        
        # 3. [핵심] 파드 개수 1개로 고정 (Pending 문제 해결)
        - name: provisioner.replicaCount
          value: "1"

        # 4. [신규] 포트 충돌 방지 (NodePlugin과 겹치지 않게 변경)
        # NodePlugin이 이미 8080, 8081을 쓰고 있으므로 9000번대로 변경
        - name: provisioner.httpMetrics.containerPort
          value: "9081"
        - name: provisioner.httpMetrics.service.servicePort
          value: "9080"

        # 5. 특정 노드에만 배포
        - name: provisioner.nodeSelector.kubernetes\.io/hostname
          value: "worker-in-ceph"
        - name: nodeplugin.nodeSelector.kubernetes\.io/hostname
          value: "worker-in-ceph"

        # 6. 파일시스템 이름 명시
        - name: storageClass.fsName
          value: "cephfs"
          
  destination:
    server: https://kubernetes.default.svc
    namespace: ceph-csi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true