apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cloud-bursting-rules
  namespace: monitoring
  labels:
    release: onprem-dev-kube-prometheus-stack
spec:
  groups:
    - name: bursting-logic
      rules:
        - alert: HostHighCpuLoad
          expr: instance:node_cpu_utilisation:rate5m > 0.9  # 90% 초과 시
          for: 5m
          labels:
            severity: critical