namespaces:
  gateway:
    enabled: true
    annotations:
      argocd.argoproj.io/sync-wave: "-10"
      argocd.argoproj.io/sync-options: Prune=false
    labels:
      purpose: envoy-proxy

  auth:
    enabled: true
    annotations:
      argocd.argoproj.io/sync-wave: "-10"
    labels:
      gateway: user

  employee:
    enabled: true
    annotations:
      argocd.argoproj.io/sync-wave: "-10"
    labels:
      gateway: user

  photo:
    enabled: true
    annotations:
      argocd.argoproj.io/sync-wave: "-10"
    labels:
      gateway: user

  argo-rollouts:
    enabled: true
    annotations:
      argocd.argoproj.io/sync-wave: "-10"
    labels:
      purpose: infra

  envoy-gateway-system:
    enabled: true
    annotations:
      argocd.argoproj.io/sync-wave: "-10"
    labels:
      purpose: gateway-control-plane

  monitoring:
    enabled: true
    annotations:
      argocd.argoproj.io/sync-wave: "-10"
    labels:
      purpose: observability

  loki:
    enabled: true
    annotations:
      argocd.argoproj.io/sync-wave: "-10"
    labels:
      purpose: logging

  fluent-bit:
    enabled: true
    annotations:
      argocd.argoproj.io/sync-wave: "-10"
    labels:
      purpose: logging

  common:
    enabled: true
    annotations:
      argocd.argoproj.io/sync-wave: "-10"
    labels:
      purpose: redis
