# values.yaml
replicaCount: 1

image:
  repository: ghcr.io/hanazzang/employee_server
  pullPolicy: Always
  tag: "sha-96f166a"

service:
  type: ClusterIP
  port: 5002

containerPort: 5002

# 참조할 ConfigMap과 Secret 이름
configs:
  dbConfig: db-config
  redisConfig: redis-config
  dbCredentials: db-credentials

  imagePullSecrets:
  - name: ghcr-pull