apiVersion: v1
kind: Service
metadata:
  name: burst-controller
  namespace: monitoring
  labels:
    app: burst-controller
spec:
  selector:
    app: burst-controller
  ports:
    - name: http
      port: 5000
      targetPort: 80
