# 수정된 values.yaml
replicaCount: 1

image:
  repository: ghcr.io/hanazzang/employee_server
  pullPolicy: Always
  tag: "sha-758193e"

imagePullSecrets:
  - name: ghcr-pull

service:
  type: ClusterIP
  port: 5002

containerPort: 5002

configs:
  dbConfig: db-config
  redisConfig: redis-config
  dbCredentials: db-credentials

# ===== HPA =====
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  cpu:
    averageUtilization: 50
  memory:
    averageUtilization: 70