apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "employee-server.fullname" . }}
  namespace: employee
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "employee-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "employee-server.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: 5002
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configs.dbConfig }}
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configs.dbConfig }}
                  key: DB_NAME
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configs.dbConfig }}
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.configs.dbCredentials }}
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.configs.dbCredentials }}
                  key: DB_PASSWORD
          envFrom:
            - configMapRef:
                name: {{ .Values.configs.redisConfig }}
  strategy:
    canary:
      # 실제 클러스터에 생성된 서비스 이름으로 하드코딩
      stableService: onprem-dev-employee-employee-server-stable
      canaryService: onprem-dev-employee-employee-server-canary
      trafficRouting:
        plugins:
          argoproj-labs/gatewayAPI:
            httpRoute: employee-route
            namespace: employee
      steps:
        - setWeight: 10
        - pause: { duration: 30s }
        - setWeight: 100