apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "employee-server.fullname" . }}
  namespace: employee
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "employee-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "employee-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}-------------------------------------------
          envFrom:
            - configMapRef:
                name: {{ .Values.configs.redisConfig }}
  strategy:
    canary:
      stableService: {{ include "employee-server.fullname" . }}-stable
      canaryService: {{ include "employee-server.fullname" . }}-canary
      trafficRouting:
        plugins:
          argoproj-labs/gatewayAPI:
            # HTTPRoute 이름은 하드코딩 해도 되지만, 위 파일과 일치해야 함
            httpRoute: employee-route 
            namespace: employee
      steps:
        - setWeight: 10
        - pause: { duration: 30s }
        - setWeight: 100