apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "employee-server.fullname" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    {{- include "employee-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "employee-server.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "employee-server.fullname" . }}
        {{- include "employee-server.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "employee-server.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          envFrom:
            {{- toYaml .Values.envFrom | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

  strategy:
    canary:
      stableService: {{ include "employee-server.fullname" . }}-stable
      canaryService: {{ include "employee-server.fullname" . }}-canary
      trafficRouting:
        plugins:
          argoproj-labs/gatewayAPI:
            # [중요] Auth와 겹치지 않게 employee 라우트 지정
            httpRoute: employee-route
            namespace: employee
      steps:
        - setWeight: 10
        - pause: { duration: 30s }
        - setWeight: 30
        - pause: { duration: 30s }
        - setWeight: 60
        - pause: { duration: 30s }
        - setWeight: 100