apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: employee-route
  namespace: employee
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: service-gateway
      namespace: gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /employee
      filters:                # 이 섹션을 추가하세요
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefix: /employee
      backendRefs:
          - group: ""
            kind: Service
            name: {{ include "employee-server.fullname" . }}-stable
            port: {{ .Values.service.port }}
            weight: 100
          - group: ""
            kind: Service
            name: {{ include "employee-server.fullname" . }}-canary
            port: {{ .Values.service.port }}
            weight: 0