apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: employee-route
  namespace: employee
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: service-gateway
      namespace: gateway
  hostnames:
    - api.yxngjxe.store
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/employee
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefix: /employee  # 앱이 /employee 경로를 사용하는 경우
      backendRefs:
        - group: ""
          kind: Service
          name: onprem-dev-employee-employee-server-stable
          port: 5002
          weight: 100
        - group: ""
          kind: Service
          name: onprem-dev-employee-employee-server-canary
          port: 5002
          weight: 0