apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: employee
data:
  # 세션: Sentinel
  REDIS_SENTINEL_HOST: "redis-sentinel-service"
  REDIS_SENTINEL_PORT: "26379"
  REDIS_MASTER_NAME: "mymaster"
  REDIS_PASSWORD: "kosa1004"

  # 캐시: 단독 Redis
  REDIS_CACHE_HOST: "redis-cache-service.common.svc.cluster.local"
  REDIS_CACHE_PORT: "6379"
