apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-alert
  namespace: monitoring
  labels:
    release: onprem-dev-kube-prometheus-stack
spec:
  groups:
    - name: test.rules
      rules:
        - alert: TestEmailAlert
          expr: vector(1)
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "Test Alert"
            description: "Alertmanager routing test (vector(1))."
