apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          volumeMounts:
            - name: data-storage
              mountPath: {{ .Values.persistence.mountPath }} # values에서 참조
      volumes:
        - name: data-storage
          persistentVolumeClaim:
            claimName: {{ include "my-chart.fullname" . }}-pvc