apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-chart.fullname" . }}-ceph-secret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/rbd
stringData:
  userID: {{ .Values.ceph.auth.userId | quote }}
  userKey: {{ .Values.ceph.auth.userKey | quote }}