gateway:
  name: main-gateway
  namespace: gateway
  gatewayClassName: envoy

  listeners:
    - name: http
      port: 80
      protocol: HTTP
      hostname: null

    - name: https
      port: 443
      protocol: HTTPS
      hostname: null
      tls:
        mode: Terminate
        secretName: wildcard-tls   # dev에서는 없어도 됨(HTTPS listener를 끄거나 secret 만들면 됨)
