gateway:
  name: service-gateway
  namespace: gateway
  gatewayClassName: envoy

  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              gateway: user

envoyProxy:
  name: envoy-gw-infra
  namespace: envoy-gateway-system
  replicas: 2
  service:
    type: ClusterIP
  podLabels:
    app: envoy-gw-dataplane
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/component: proxy