apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-scenario-config
  namespace: k6
data:
   k6-rampup.js: |
    import http from 'k6/http';
    import { check, sleep } from 'k6';

    export const options = {
      stages: [
        { duration: '2m', target: 50 },  // Warm-up
        { duration: '5m', target: 500 }, // Stress 구간
        { duration: '2m', target: 0 },   // Cool-down
      ],
    };

    export default function () {
      // Envoy Ingress 주소
      const res = http.get('https://yongun.shop/api/employee');
      check(res, { 'status was 200': (r) => r.status == 200 });
      sleep(1);
    }