gateway:
  name: service-gateway
  namespace: gateway
  gatewayClassName: envoy

  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              gateway: user

    - name: https
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              gateway: user
      tls:
        mode: Terminate
        secretName: api-yxngjxe-tls # gateway 네임스페이스에 이 Secret이 반드시 있어야 함

envoyProxy:
  name: envoy-gw-infra
  namespace: gateway
  replicas: 2
  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.1.199
  podLabels:
    app: envoy-gw-dataplane
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/component: proxy