apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      serviceAccountName: auth-sa
      containers:
      - name: auth-server
        image: ghcr.io/hanazzang/auth_server:sha-758193e
        ports:
        - containerPort: 5001
        envFrom:
        - configMapRef:
            name: db-config
        - secretRef:
            name: db-credentials
        resources:
          limits:
            memory: "512Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"