apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "auth-server.fullname" . }}
  labels:
    {{- include "auth-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "auth-server.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "auth-server.fullname" . }}
        {{- include "auth-server.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: {{ include "auth-server.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}

          envFrom:
{{- toYaml .Values.envFrom | nindent 12 }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
