apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-cache.fullname" . }}
  namespace: {{ .Values.namespace | default "common" }}
spec:
  selector:
    {{- include "redis-cache.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6379
