apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: photo-service-chaos-schedule
  namespace: chaos-mesh
spec:
  schedule: "0 2 * * *" # 매일 새벽 2시 실행
  historyLimit: 3
  concurrencyPolicy: "Forbid"
  networkChaos: # 장애 유형 정의
    action: delay
    mode: one
    selector:
      namespaces:
        - photo
      labelSelectors:
        'app.kubernetes.io/name': 'photo-service'
    delay:
      latency: "150ms"
    duration: "10m" # 10분 후 자동 복구