apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-receive
  namespace: monitoring
  labels:
    app.kubernetes.io/name: thanos-receive
spec:
  serviceName: thanos-receive
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: thanos-receive
  template:
    metadata:
      labels:
        app.kubernetes.io/name: thanos-receive
    spec:
      containers:
        - name: thanos
          image: quay.io/thanos/thanos:v0.37.2
          args:
            - receive
            - --log.level=info
            - --tsdb.path=/data
            - --receive.hashrings-file=/etc/thanos/hashring.json
            - --receive.replication-factor=1
            # - --label=receive_replica="0"

            # ✅ EKS Prometheus agent가 remote_write로 보내는 엔드포인트
            - --remote-write.address=0.0.0.0:19291

            # ✅ Query가 붙는 StoreAPI(gRPC)
            - --grpc-address=0.0.0.0:10901

            # (옵션) Receive 자체 상태 페이지/metrics
            - --http-address=0.0.0.0:10902
          ports:
            - name: remote-write
              containerPort: 19291
            - name: grpc
              containerPort: 10901
            - name: http
              containerPort: 10902
          volumeMounts:
            - name: data
              mountPath: /data
            - name: hashring
              mountPath: /etc/thanos
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
      volumes:
        - name: data
          emptyDir: {}
        - name: hashring
          configMap:
            name: thanos-receive-hashring
  # volumeClaimTemplates:
  #   - metadata:
  #       name: data
  #     spec:
  #       accessModes: ["ReadWriteOnce"]
  #       storageClassName: local-storage
  #       resources:
  #         requests:
  #           storage: 50Gi
