apiVersion: v1
kind: Service
metadata:
  name: thanos-receive-nodeport
  namespace: monitoring
  labels:
    app.kubernetes.io/name: thanos-receive
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: thanos-receive
  ports:
    - name: remote-write
      port: 19291
      targetPort: 19291
      nodePort: 31291
