apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. 시나리오 파일 설정
configMapGenerator:
  - name: locust-scenario-config
    files:
      - locustfile.py

# 2. 이름 해시 제거 설정 (들여쓰기 주의!)
generatorOptions:
  disableNameHash: true

namespace: locust