apiVersion: v1
kind: Service
metadata:
  name: {{ include "photo-server.fullname" . }}-active
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    {{- include "photo-server.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ include "photo-server.fullname" . }}