# templates/deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: photo-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: photo-service
  template:
    metadata:
      labels:
        app: photo-service
    spec:
      serviceAccountName: photo-sa
      containers:
      - name: photo-service
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5003
        volumeMounts:
        - name: photo-storage
          mountPath: /app/static/uploads
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      volumes:
      - name: photo-storage
        persistentVolumeClaim:
          claimName: photo-pvc