apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "photo-service.fullname" . }}
  labels:
    {{- include "photo-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "photo-service.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "photo-service.fullname" . }}
        {{- include "photo-service.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: {{ include "photo-service.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          volumeMounts:
            - name: photo-storage
              mountPath: {{ .Values.persistence.mountPath }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: photo-storage
          persistentVolumeClaim:
            claimName: {{ include "photo-service.fullname" . }}-pvc
  strategy:
    blueGreen:
      activeService: {{ include "photo-service.fullname" . }}-active
      previewService: {{ include "photo-service.fullname" . }}-preview

      # 새 버전(Preview) 올려놓고 확인 후 Promote로 스위치
      autoPromotionEnabled: false

      # 스위치 후 기존 ReplicaSet을 잠깐 유지(롤백 빠르게)
      scaleDownDelaySeconds: 30