apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: photo-route
  namespace: photo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: service-gateway
      namespace: gateway
  hostnames:
    - {{ .Values.ingress.host | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/photo
      filters:
        # [기능] /api/photo/upload -> /photo/upload 로 변경하여 컨테이너 전달
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /photo
      backendRefs:
        # [중요] 항상 active(Blue) 서비스를 바라봐야 함
        - group: ""
          kind: Service
          name: {{ include "photo-service.fullname" . }}-active
          port: {{ .Values.service.port }}
          weight: 100