{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "photo-service.fullname" . }}-pvc
  labels:
    {{- include "photo-service.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  accessModes:
    # values.yaml에서 "ReadWriteMany"를 가져옴
    - {{ .Values.persistence.accessMode | default "ReadWriteMany" }}
  storageClassName: {{ .Values.persistence.storageClass | default "csi-cephfs-sc" }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "1Gi" }}
{{- end }}