# templates/pv-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: photo-ceph-sc
  resources:
    requests:
      storage: 1Gi