apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "{{ .Values.storageClass.isDefault }}"
    argocd.argoproj.io/sync-wave: "-10" # PVC보다 먼저 생성되어야 함
provisioner: {{ .Values.storageClass.provisioner }}
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
volumeBindingMode: {{ .Values.storageClass.bindingMode }}
allowVolumeExpansion: {{ .Values.storageClass.allowVolumeExpansion }}
parameters:
  {{- range $key, $value := .Values.storageClass.parameters }}
  {{ $key }}: "{{ $value }}"
  {{- end }}