envoyProxy:
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"

monitoring:
  podMonitor:
    enabled: true

autoscaling:
  enabled: false

keda:
  enabled: false
  triggers: []