{{- range $name, $ns := .Values.namespaces }}
{{- if $ns.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $name | quote }}
{{- if $ns.annotations }}
  annotations:
{{ toYaml $ns.annotations | nindent 4 }}
{{- end }}
{{- if $ns.labels }}
  labels:
{{ toYaml $ns.labels | nindent 4 }}
{{- end }}
---
{{- end }}
{{- end }}