{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-loki-gateway
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-loki
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.gateway.type | default "LoadBalancer" }}
  ports:
    - name: http
      port: {{ .Values.gateway.port | default 3100 }}
      targetPort: 3100
      protocol: TCP
      {{- if and (.Values.gateway.nodePort) (eq (.Values.gateway.type | default "LoadBalancer") "NodePort") }}
      nodePort: {{ .Values.gateway.nodePort }}
      {{- end }}
  selector:
    app: {{ .Release.Name }}-loki
{{- end }}
