{{- if .Values.tokenReviewer.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.tokenReviewer.name }}
  namespace: {{ .Values.tokenReviewer.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.tokenReviewer.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: {{ .Values.tokenReviewer.name }}
    namespace: {{ .Values.tokenReviewer.namespace }}
{{- end -}}
