apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: onprem-dev-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/hanazzang/BABAMBA-gitops
        revision: argos-test
        directories:
          - path: clusters/onprem/dev/apps/*
  template:
    metadata:
      name: 'onprem-dev-{{path.basename}}'
    spec:
      project: default

      sources:
        - repoURL: https://github.com/hanazzang/BABAMBA-gitops
          targetRevision: argos-test
          path: charts/{{path.basename}}
          helm:
            valueFiles:
              - $values/{{path}}/values.yaml

        - repoURL: https://github.com/hanazzang/BABAMBA-gitops
          targetRevision: argos-test
          ref: values
          path: clusters

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      
      ignoreDifferences:
        - group: monitoring.coreos.com
          kind: PodMonitor
          jqPathExpressions:
            - .spec.podMetricsEndpoints[]?.relabelings
        - group: argoproj.io
          kind: Rollout
          jsonPointers:
            - /spec/replicas

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
