apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onprem-dev-keda
  namespace: argocd
  annotations:
    # 모니터링/메트릭 준비 이후 설치
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: keda

  sources:
    - repoURL: https://kedacore.github.io/charts
      chart: keda
      targetRevision: 2.18.3
      helm:
        releaseName: keda
        valueFiles:
          - $values/clusters/onprem/dev/platform/keda/values.yaml

    - repoURL: https://github.com/hanazzang/BABAMBA-gitops
      targetRevision: refactor/gitops-structure
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
