apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: onprem-dev-monitoring-stack
  namespace: argocd
spec:
  generators:
    # 깃레포에 monitoring 폴더가 있는지 확인해서 트리거
    - git:
        repoURL: https://github.com/hanazzang/BABAMBA-gitops
        revision: refactor/gitops-structure
        directories:
          - path: clusters/onprem/dev/platform/monitoring
  template:
    metadata:
      name: 'onprem-dev-monitoring'
    spec:
      project: default
      source:
        repoURL: https://github.com/hanazzang/BABAMBA-gitops
        targetRevision: refactor/gitops-structure
        path: platform/monitoring
        
        helm:
          valueFiles:
            - ../../clusters/onprem/dev/platform/monitoring/values.yaml

      destination:
        server: https://kubernetes.default.svc
        namespace: monitoring

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true