apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: observability-resources
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/hanazzang/BABAMBA-gitops
        revision: refactor/gitops-structure
        directories:
          - path: clusters/onprem/dev/platform/monitoring 
  template:
    metadata:
      name: 'onprem-dev-observability'
    spec:
      project: default
      source:
        repoURL: https://github.com/hanazzang/BABAMBA-gitops
        targetRevision: refactor/gitops-structure
        path: platform/observability
      destination:
        server: https://kubernetes.default.svc
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true