apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-resources
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/hanazzang/BABAMBA-gitops
        revision: refactor/gitops-structure
        directories:
          - path: clusters/onprem/dev/platform/*

  template:
    metadata:
      name: 'onprem-dev-{{path.basename}}'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/hanazzang/BABAMBA-gitops
          targetRevision: refactor/gitops-structure
          path: platform/{{path.basename}}
          helm:
            ignoreMissingValueFiles: true
            valueFiles:
              # env(클러스터)별 오버라이드 값 적용
              - $values/{{path}}/values.yaml
              # autoscaling 스위치/트리거(선택). 없으면 무시됩니다.
              - $values/{{path}}/values-autoscaling.yaml
        - repoURL: https://github.com/hanazzang/BABAMBA-gitops
          targetRevision: refactor/gitops-structure
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      ignoreDifferences:
        - group: monitoring.coreos.com
          kind: PodMonitor
          jqPathExpressions:
            - .spec.podMetricsEndpoints[]?.relabelings
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/replicas
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true