apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-resources
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/hanazzang/BABAMBA-gitops
        revision: hpa2

        directories:
          - path: clusters/onprem/dev/platform/*
          - path: clusters/onprem/dev/platform/keda
            exclude: true
          - path: clusters/onprem/dev/platform/monitoring
            exclude: true

  template:
    metadata:
      name: 'onprem-dev-{{path.basename}}'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/hanazzang/BABAMBA-gitops
          targetRevision: hpa2

          path: platform/{{path.basename}}
          helm:
            valueFiles:
              - $values/platform/{{path.basename}}/values.yaml
              - $values/{{path}}/values.yaml
        - repoURL: https://github.com/hanazzang/BABAMBA-gitops
          targetRevision: hpa2

          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      ignoreDifferences:
        - group: monitoring.coreos.com
          kind: PodMonitor
          jqPathExpressions:
            - .spec.podMetricsEndpoints[]?.relabelings
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/replicas
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
