apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-resources
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/hanazzang/BABAMBA-gitops
        revision: monitoring2
        directories:
          - path: clusters/onprem/dev/platform/*
  template:
    metadata:
      name: 'onprem-dev-{{path.basename}}'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/hanazzang/BABAMBA-gitops
          targetRevision: monitoring2
          path: platform/{{path.basename}}
          helm:
            valueFiles:
              - $values/platform/{{path.basename}}/values.yaml
              - $values/{{path}}/values.yaml
        - repoURL: https://github.com/hanazzang/BABAMBA-gitops
          targetRevision: monitoring2
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
