apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: {{ .Values.nodeClass.amiFamily | default "AL2" | quote }}

  amiSelectorTerms:
    - alias: {{ .Values.nodeClass.amiAlias | default "al2@latest" | quote }}

  role: {{ required "aws.nodeRole is required" .Values.aws.nodeRole | quote }}

  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ required "clusterName is required" .Values.clusterName | quote }}

  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ required "clusterName is required" .Values.clusterName | quote }}