apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ceph-csi
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://ceph.github.io/csi-charts
    chart: ceph-csi-cephfs
    targetRevision: 3.16.0
    helm:
      parameters:
        - name: csiConfig[0].clusterID
          value: "491b725b-d483-48ea-855a-b78b5b1bdc91"
        - name: csiConfig[0].monitors[0]
          value: "10.10.10.101:6789" # Proxmox Node 1
        - name: csiConfig[0].monitors[1]
          value: "10.10.10.102:6789" # Proxmox Node 2
        - name: csiConfig[0].monitors[2]
          value: "10.10.10.103:6789" # Proxmox Node 2
  destination:
    server: https://kubernetes.default.svc
    namespace: ceph-csi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true