apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chaos-mesh
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.chaos-mesh.org
    targetRevision: 2.8.1
    chart: chaos-mesh
    helm:
      values: |
        controllerManager:
            nodeSelector:
              node-role.kubernetes.io/control-plane: "" # 마스터 노드에 배치
            tolerations:
              - key: "node-role.kubernetes.io/control-plane"
                operator: "Exists"
                effect: "NoSchedule"
        chaosDaemon:
          runtime: containerd # 사용하는 런타임에 맞게 수정 (containerd/docker)
          socketPath: /run/containerd/containerd.sock
        dashboard:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: chaos-mesh
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true