apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
spec:
  project: default
  source:
    chart: gateway-helm
    repoURL: docker.io/envoyproxy
    targetRevision: v1.6.2
    helm:
      values: |
        config:
          envoyGateway:
            provider:
              kubernetes:
                deploy:
                  type: GatewayNamespace
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true   # EKS 등 원격 클러스터에 namespace 없을 때 Argo가 생성
      - ServerSideApply=true

