apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k6-test-run
  namespace: argocd
spec:
  project: default
  sources:
    # 1. k6 실행 명령(K6 CRD)과 ConfigMap(JS파일)이 있는 내 Git 경로
    - repoURL: https://github.com/hanazzang/BABAMBA-gitops
      targetRevision: monitoring2
      path: platform/k6 # kustomization.yaml과 k6-run.yaml이 있는 곳
  destination:
    server: https://kubernetes.default.svc
    namespace: k6