apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onprem-dev-keda
  namespace: argocd
  annotations:
    # kube-prometheus-stack 이후(메트릭 기반 스케일링이므로)
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: keda

  sources:
    - repoURL: https://kedacore.github.io/charts
      chart: keda
      # 버전 고정 추천
      targetRevision: 2.18.3
      helm:
        releaseName: keda
        valueFiles:
          - $values/clusters/onprem/dev/platform/keda/values.yaml

    - repoURL: https://github.com/hanazzang/BABAMBA-gitops
      targetRevision: argos-test
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
