apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onprem-dev-kps-crds
  namespace: argocd

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring  # CRD는 클러스터 스코프라 ns 의미는 거의 없음

  source:
    repoURL: https://github.com/hanazzang/BABAMBA-gitops
    targetRevision: monitoring2
    path: platform/kps-crds/crds

  syncPolicy:
    automated: {}
    syncOptions:
      - ServerSideApply=true
      - Replace=true
      - Prune=false   # CRD는 절대 자동 삭제 금지

  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jqPathExpressions:
        - .status
        - .metadata.annotations