apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hanazzang/BABAMBA-gitops
    path: platform/storage # 실제 StorageClass 야물이 있는 경로
    targetRevision: monitoring2-cloud


  destination:
    server: https://kubernetes.default.svc
    namespace: default # SC는 전역 리소스지만 앱 등록을 위해 지정 (보통 default)
  syncPolicy:
    automated:
      prune: true
      selfHeal: true