apiVersion: v2
name: karpenter
version: 0.1.0
type: application
appVersion: 1.0.5  

dependencies:
  - name: karpenter
    alias: upstream
    repository: oci://public.ecr.aws/karpenter/karpenter
    version: "1.0.5" 