apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: gmail
  namespace: monitoring
  labels:
    # values-kps.yaml의 alertmanagerConfigSelector와 일치하도록 설정
    release: onprem-dev-kube-prometheus-stack 
spec:
  route:
    receiver: gmail
    groupBy: ["alertname", "cluster", "pod"]
    groupWait: 10s
    groupInterval: 3m
    repeatInterval: 2h
    routes:
      - receiver: gmail
        matchers:
          - name: severity
            value: warning
            matchType: "="
        continue: true

  receivers:
    - name: gmail
      emailConfigs:
        - to: "sieun6213@naver.com"
          from: "sieun6213@gmail.com"
          smarthost: "smtp.gmail.com:587"
          authUsername: "sieun6213@gmail.com"
          authPassword:
            name: alertmanager-gmail
            key: smtp_pass
          headers:
            - key: "Subject"
              # 👇 Helm이 해석하지 못하도록 이중 중괄호 처리 적용
              value: '[{{ "{{" }} .Status | toUpper {{ "}}" }}{{ "{{" }} if eq .Status "firing" {{ "}}" }}:{{ "{{" }} .Alerts.Firing | len {{ "}}" }}{{ "{{" }} end {{ "}}" }}] {{ "{{" }} .CommonLabels.alertname {{ "}}" }} ({{ "{{" }} .CommonLabels.cluster {{ "}}" }} / {{ "{{" }} .CommonLabels.pod {{ "}}" }})'
          requireTLS: true
          sendResolved: true