# ===== 기본 스케일 =====
replicaCount: 1

# ===== 이미지 =====
image:
  repository: ghcr.io/hanazzang/photo_service
  tag: "sha-29544c2"
  pullPolicy: IfNotPresent

# ===== 서비스 계정 =====
serviceAccount:
  name: photo-sa

# ===== 서비스 포트 =====
service:
  port: 5003
  targetPort: 5003

ingress:
  host: api.yongun.shop

# ===== 스토리지 (NFS RWX로 수정) =====
# 이제 여러 노드에서 동시에 접근 가능(RWX)하며, 데이터가 VM에 안전하게 저장됩니다.
persistence:
  enabled: true
  storageClassName: "nfs-client"
  accessMode: ReadWriteMany  # [중요] 여러 파드가 동시에 쓸 수 있게 RWX로 설정
  size: 1Gi
  mountPath: /app/static/uploads

# [NFS 실제 정보] - PV 템플릿에서 참조할 값들
pvName: "photo-service-pv"
nfsServer: "192.168.1.147"  # <--- 여기에 NFS VM IP를 꼭 넣어주세요!
nfsPath: "/data/nfs/photo"   # <--- NFS 서버에서 설정한 경로