apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/hanazzang/BABAMBA-gitops
    targetRevision: hana
    path: clusters/cloud/prod/platform/aws-load-balancer-controller
    helm:
      chart: aws-load-balancer-controller
      repoURL: https://aws.github.io/eks-charts
      targetRevision: 1.7.2
      valueFiles:
        - values.yaml
      parameters:
        - name: clusterName
          value: hana-eks-dev-usw2-eks
        - name: region
          value: us-west-2
        - name: vpcId
          value: vpc-00e7f160b941024ee
        - name: serviceAccount.create
          value: "false"
        - name: serviceAccount.name
          value: aws-load-balancer-controller

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
