# applications/cloud-prod/kps-crds.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-prod-kps-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0" # 가장 먼저 설치
spec:
  project: default
  source:
    repoURL: https://github.com/hanazzang/BABAMBA-gitops
    targetRevision: argos-test
    path: platform/kps-crds/crds # 공용 CRD 경로 재사용
  destination:
    server: https://kubernetes.default.svc # eks클러스터 주소
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true # CRD는 크기가 커서 필수