# applications/cloud-prod/kps-crds.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-prod-kps-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0" # 가장 먼저 설치
spec:
  project: default
  source:
    repoURL: https://github.com/hanazzang/BABAMBA-gitops
    targetRevision: hpa2



    path: platform/kps-crds/crds # 공용 CRD 경로 재사용
  destination:
    # 온프 ArgoCD가 EKS 원격 관리 시 ips.env 의 EKS_CLUSTER_URL 로 채움 (ipctl apply)
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true # CRD는 크기가 커서 필수