apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-prod-observability
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10" # KPS(에이전트) 설치 후 실행
spec:
  project: default
  source:
    repoURL: https://github.com/hanazzang/BABAMBA-gitops
    targetRevision: hpa2

    path: workloads/monitoring/eks # EKS용 모니터링 리소스 경로
  destination:
    # cloud-prod: ArgoCD가 같은 클러스터에 설치된 전제(in-cluster)
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true