apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-prod-observability
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10" # KPS(에이전트) 설치 후 실행
spec:
  project: default
  source:
    repoURL: https://github.com/hanazzang/BABAMBA-gitops
    targetRevision: monitoring2
    path: workloads/monitoring/eks # EKS용 모니터링 리소스 경로
  destination:
    server: https://14aafe276b19e2c2cf3864df93f31b1c.gr7.us-west-2.eks.amazonaws.com/
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true