apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-warmup
  namespace: common
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-warmup
  template:
    metadata:
      labels:
        app: redis-warmup
    spec:
      containers:
      - name: warmup
        image: ooweajzzang/redis-warmup:1.0
        imagePullPolicy: Always
