apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy-gw-infra
  namespace: envoy-gateway-system
  annotations:
    argocd.argoproj.io/sync-wave: "-6"
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: ClusterIP