apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: employee-write
  namespace: k6
spec:
  parallelism: 10
  cleanup: post
  paused: false
  quiet: false

  script:
    configMap:
      name: k6-hpa-test-scenario
      file: k6-hpa-employee-multiid.js

  runner:
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: "1"
        memory: 2Gi

  arguments: >
    -e TEST_MODE=employee_write
    -e USERS=1000
    -e DURATION=2m
    -e TIMEOUT=10s
    -e WRITES_PER_SEC=0.2
    -e PHOTO_PCT=90
    -e POST_THEN_GET_PCT=0
    -e AUTH_BASE=http://auth-server-stable.auth.svc:5001
    -e AUTH_LOGIN_PATH=/auth/login
    -e HOST_HEADER=api.yongun.shop
    -e EMP_WRITE_URL=http://service-gateway.gateway.svc.cluster.local/employee/employee
    -e USER_PREFIX=k6_user_
    -e PASS_PREFIX=k6_pass_
    -e USER_PAD=6
