apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: employee-get
  namespace: k6
spec:
  parallelism: 10
  cleanup: post
  paused: "false"
  quiet: "false"

  script:
    configMap:
      name: k6-hpa-test-scenario
      file: k6-hpa-employee-multiid.js

  runner:
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: "1"
        memory: 2Gi

  arguments: >
    -e TEST_MODE=employee_get
    -e USERS=300
    -e DURATION=2m
    -e TIMEOUT=10s
    -e GETS_PER_SEC=5
    -e AUTH_BASE=http://auth-server-stable.auth.svc:5001
    -e AUTH_LOGIN_PATH=/auth/login
    -e HOST_HEADER=api.yongun.shop
    -e EMP_GET_URL=http://service-gateway.gateway.svc.cluster.local/employee/employees
    -e USER_PREFIX=k6_user_
    -e PASS_PREFIX=k6_pass_
    -e USER_PAD=6
