apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: gateway-only
  namespace: k6
spec:
  parallelism: 10
  cleanup: post

  script:
    configMap:
      name: k6-hpa-test-scenario
      file: k6-hpa-employee-multiid.js

  runner:
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: "1"
        memory: 2Gi

  arguments: >
    -e TEST_MODE=gateway_only
    -e USERS=1000
    -e DURATION=2m
    -e TIMEOUT=10s
    -e GETS_PER_SEC=100
    -e HOST_HEADER=api.yongun.shop
    -e GATEWAY_URL=https://service-gateway.gateway.svc.cluster.local:443/gateway-health
    -e GATEWAY_NEEDS_AUTH=false
