upstream:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/<KARPENTER_CONTROLLER_ROLE>

  settings:
    clusterName: "hana-eks-dev-usw2"
    clusterEndpoint: "https://<EKS_ENDPOINT>"
    interruptionQueue: "<KARPENTER_INTERRUPTION_QUEUE_NAME>"