upstream:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::438296477852:role/karpenter_controller_role

  settings:
    clusterName: hana-eks-dev-usw2
    clusterEndpoint: https://B7567E2D3F5A2368EC5121B4DB7D8FF9.gr7.us-west-2.eks.amazonaws.com
    interruptionQueue: karpenter-interruption-queue