crds:
  enabled: false

grafana:
  enabled: true
  service:
    type: NodePort
    nodePort: 32300
  # 사이드카 설정(커스텀한 대시보드 사용)
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard

  # 로그인 강제 + 계정 생성 금지
  grafana.ini:
    auth.anonymous:
      enabled: false
    users:
      allow_sign_up: false
      allow_org_create: false

  # admin 비번은 Secret에서만
  admin:
    existingSecret: grafana-admin-secret
    userKey: admin-user
    passwordKey: admin-password

  # Grafana 대시보드와 사용자 설정 보존용 스토리지
  persistence:
    # 데모 버전 false설정, 실 테스트에선 true로 변경하고 아래 주석 풀기
    enabled: false
    # storageClassName: "ceph" # Ceph StorageClass
    # size: 10Gi



prometheus:
  prometheusSpec:
    # EKS 데이터를 받기 위한 필수 설정
    enableFeatures:
      - remote-write-receiver

    # 튜닝 적용: 수집 주기 완화 및 보존 기간 최적화
    scrapeInterval: "30s"
    evaluationInterval: "30s"

    # 데이터 보존 기간 최적화
    retention: "7d"

    # [알림 고도화] 모든 알림에 클러스터 이름 강제 삽입
    externalLabels:
      cluster: "onprem-dev" # 나중에 환경명 바뀔 때 여기만 수정

    replicas: 1
    resources:
      requests:
        cpu: "300m"
        memory: "1Gi"
      limits:
        cpu: "1000m"
        memory: "2Gi"

    # 스토리지 쓰려면 아래 주석 해제
    storageSpec:
      # 데모용 임시 디렉터리 
      emptyDir:
        medium: ""
      # ceph 스토리지
      # volumeClaimTemplate:
      #   spec:
      #     storageClassName: "ceph"   # Ceph StorageClass
      #     accessModes: ["ReadWriteOnce"]
      #     resources:
      #       requests:
      #         storage: 80Gi

    # 모든 네임스페이스의 ServiceMonitor 자동 감지
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    

alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 1
    alertmanagerConfigSelector:
      matchLabels:
        release: onprem-dev-kube-prometheus-stack

# 데모 환경에서 불필요한 고부하 수집기 비활성화
kubeProxy:
  enabled: false
kubeScheduler:
  enabled: false
kubeControllerManager:
  enabled: false

# kube-state-metrics / node-exporter 등은 기본 포함