apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubernetes-event-exporter.fullname" . }}
  labels:
    {{- include "kubernetes-event-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kubernetes-event-exporter.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "kubernetes-event-exporter.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kubernetes-event-exporter.fullname" . }}
      containers:
        - name: exporter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-conf=/config/config.yaml"
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "kubernetes-event-exporter.fullname" . }}

