# ===== 기본 스케일 =====
replicaCount: 1

# ===== 이미지 (환경별 핵심 값) =====
image:
  repository: ghcr.io/hanazzang/auth_server
  tag: "sha-2e30ade"
  pullPolicy: IfNotPresent

# ===== 서비스 계정 =====
serviceAccount:
  name: auth-sa

# ===== 서비스 포트 =====
service:
  port: 5001
  targetPort: 5001

# ===== 환경변수 주입 (사전 생성된 리소스) =====
envFrom:
  configMapRef:
    name: db-config
  secretRef:
    name: db-credentials

# ===== 리소스 (dev 기준) =====
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "512Mi"

# ===== HPA =====
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  cpu:
    averageUtilization: 50
  memory:
    averageUtilization: 70
