apiVersion: v2
name: envoy-gateway-system
description: Envoy Gateway Controller
type: application
version: 1.0.0
dependencies:
  - name: gateway-helm
    version: v1.6.2
    repository: oci://docker.io/envoyproxy