apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: probe-http-example
  namespace: monitoring
  labels:
    release: onprem-dev-kube-prometheus-stack
spec:
  jobName: blackbox-http
  interval: 30s
  module: http_2xx
  
  prober:
    url: blackbox-exporter.monitoring.svc:9115
  
  targets:
    staticConfig:
      static:
        - https://google.com