# ==========================================
# Deployment 관련 설정 (deployment.yaml)
# ==========================================
replicaCount: 1

image:
  repository: ghcr.io/hanazzang/photo_service
  tag: "sha-36c997e"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-pull

# ==========================================
# ServiceAccount 관련 설정 (serviceaccount.yaml)
# ==========================================

serviceAccount:
  name: photo-sa

# ==========================================
# Service 관련 설정 (service.yaml)
# ==========================================

service:
  port: 5003
  targetPort: 5003

# ==========================================
# Persistence 관련 설정 (pv-pvc.yaml & deployment.yaml)
# ==========================================
persistence:
  enabled: true
  size: 1Gi
  hostPath: /mnt/data/photos
  mountPath: /app/static/uploads

# ==========================================
# Resource 관리 설정 (deployment.yaml)
# ==========================================
resources:
  limits:
    memory: "512Mi"
    cpu: "200m"
  requests:
    memory: "128Mi"
    cpu: "100m"

# ==========================================
# Autoscaling 관련 설정 (hpa.yaml)
# ==========================================
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  cpu:
    averageUtilization: 50
  memory:
    averageUtilization: 70
