apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cloud-prod-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/hanazzang/BABAMBA-gitops
        revision: vault
        directories:
          - path: clusters/cloud/prod/apps/*
  template:
    metadata:
      name: 'cloud-prod-{{path.basename}}'
    spec:
      project: default

      sources:
        - repoURL: https://github.com/hanazzang/BABAMBA-gitops
          targetRevision: vault
          path: charts/{{path.basename}}
          helm:
            valueFiles:
              - $values/{{path}}/values.yaml

        - repoURL: https://github.com/hanazzang/BABAMBA-gitops
          targetRevision: vault
          ref: values
          path: clusters

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
