apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cloud-prod-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/hanazzang/BABAMBA-gitops
        revision: refactor/gitops-structure
        directories:
          - path: clusters/cloud/prod/apps/*
  template:
    metadata:
      name: 'cloud-prod-{{path.basename}}'
    spec:
      project: default

      sources:
        # 1) 앱 Helm Chart (charts/<app>)
        - repoURL: https://github.com/hanazzang/BABAMBA-gitops
          targetRevision: refactor/gitops-structure
          path: charts/{{path.basename}}
          helm:
            valueFiles:
              - $values/{{path}}/values.yaml

        # 2) values repo ref (clusters)
        - repoURL: https://github.com/hanazzang/BABAMBA-gitops
          targetRevision: refactor/gitops-structure
          ref: values

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'

      ignoreDifferences:
        - group: monitoring.coreos.com
          kind: PodMonitor
          jqPathExpressions:
            - .spec.podMetricsEndpoints[]?.relabelings
        - group: argoproj.io
          kind: Rollout
          jsonPointers:
            - /spec/replicas

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true