apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cloud-prod-platform-crds-generator
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/hanazzang/BABAMBA-gitops
        revision: refactor/gitops-structure
        # ✅ 폴더가 아니라 'crd.yaml' 파일 그 자체를 감시합니다.
        files:
          - path: "clusters/cloud/prod/crds/crd.yaml"
  template:
    metadata:
      # 앱 이름은 딱 하나로 고정됩니다.
      name: 'cloud-prod-all-crds'
    spec:
      project: default
      source:
        repoURL: https://github.com/hanazzang/BABAMBA-gitops
        targetRevision: refactor/gitops-structure
        # ✅ 실제 모든 CRD 폴더들이 있는 루트 경로를 바라봅니다.
        path: platform/crds 
        directory:
          recurse: true # 하위 폴더(keda, monitoring 등)를 싹 긁어옵니다.
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true