namespaces:
  # 1. Karpenter는 온프레미스에서 필요 없으므로 비활성화
  karpenter:
    enabled: false

  # 2. MetalLB는 온프레미스 핵심 인프라이므로 설정 유지/활성화
  metallb-system:
    enabled: true
    annotations:
      argocd.argoproj.io/sync-wave: "-10"
      argocd.argoproj.io/sync-options: Prune=false
    labels:
      purpose: infra