# clusters/onprem/dev/platform/namespaces/values.yaml

namespaces:  # <--- 이 부모 키가 반드시 있어야 합니다!
  - name: metallb-system
    annotations:
      argocd.argoproj.io/sync-wave: "-10"
      argocd.argoproj.io/sync-options: Prune=false
    labels:
      purpose: infra