image:
  repository: ghcr.io/resmoio/kubernetes-event-exporter
  # GHCR에서는 v1.7.0 태그가 없고 v1.7 형태로 제공됩니다.
  tag: "v1.7"
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

# Resmoio kubernetes-event-exporter config:
# - Logs events as JSON to stdout
config:
  logLevel: info
  logFormat: json
  receivers:
    - name: stdout
      stdout: {}
  route:
    routes:
      - match:
          - receiver: stdout

